url: http://enabletechnotts.github.io

# Site settings
title: Health Care
email: psxxh1@nottingham.ac.uk
description: "The coursework for Enabling Technologies in the University of Nottingham"
disqus_shortname: houxianxu

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Pepita Stringer
  pic: 1
  position: PhD Student
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Kate Arnold
  pic: 2
  position: PhD Student
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Iona Fitzpatrick
  pic: 3
  position: PhD Student
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Alex Young
  pic: 4
  position: PhD Student
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Chuang Gao
  pic: 5
  position: PhD Student
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Xianxu Hou
  pic: 6
  position: PhD Student
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Horizon CDT Centre
  - line: School of Computer Science
  - line: University of Nottingham
  - line: Jubilee Campus
  - line: Wollaton Road Nottingham   NG8 1BB

# Build settings
markdown: kramdown
permalink: pretty